### PR TITLE
feat: add `sortBy`, rework `sort` and `sortWith`

### LINKED ISSUE #10: Sort by date
I was wondering how to use `sort` / `sortBy` to sort by dates, which I believe is a common use case. I was about to open a PR but wanted to check your opinion first. 

This is what I have, for sorting objects by a given field:

```js
const sortByDate = field =>
  sort((a, b) => {
    if (isEmpty(b[field])) {
      return -1
    }

    if (isEmpty(a[field])) {
      return 1
    }

    return new Date(b[field]).getTime() - new Date(a[field]).getTime()
  })
```

which in turn takes me to consider other sorting behaviors (alphabetical?) and also if you'd add a new file for each sorting, or maybe generalize the criterium ...

### PR DESCRIPTION
**Pull request by andreidmt**
Current support for sorting object arrays is minimal and does not provide the expressiveness of other functions like `filterWith`. This introduces `sortBy` and `sortWith` to allow multiple key sorting and field level transform function.

## Changes

**1. Add function `sortBy` to sort an array using a custom compare function:**

```js
sortBy(
  (a, b) => a.position - b.position,
  [
    { id: 4, position: 5 },
    { id: 1, position: 3 },
    { id: 2, position: 2 },
  ]
)
// => [
//   { id: 2, position: 2 },
//   { id: 1, position: 3 },
//   { id: 4, position: 5 },
// ]
```

**2. Rework `sort` to only accept primitive arrays and an optional `direction` param:**

```js
sort([3, 2, 1])
// => [1, 2, 3]

sort("desc", ["a", "c", "b"])
// => ["c", "b", "a"],
```

**3. Rework `sortWith` to sort on multiple key with various signatures:**

**v1:** multiple fields with different directions

```js
sortWith(
  {
    isActive: "desc",
    position: "asc",
  },
  [
    { id: 4, position: 5, isActive: true },
    { id: 1, position: 3, isActive: true },
    { id: 3, position: 4, isActive: false },
    { id: 6, position: 0, isActive: false },
  ]
)
// => [
//   { id: 1, position: 3, isActive: true },
//   { id: 4, position: 5, isActive: true },
//   { id: 6, position: 0, isActive: false },
//   { id: 3, position: 4, isActive: false },
// ]
```

**v2:** custom compare function - 2 param signature

- function receives directly both values of the assigned key
- `null` and `undefined` get special treatment and will always be at the end of the list

```js
sortWith(
  {
    isActive: "desc",
    createdAt: (a, b) => new Date(a).getTime() - new Date(b).getTime(),
  },
  [
    { id: 5, createdAt: "12-02-2010", isActive: false },
    { id: 4, createdAt: "12-02-2011", isActive: true },
    { id: 6, createdAt: "12-02-2005", isActive: false },
    { id: 2, createdAt: "12-02-2003", isActive: true },
    { id: 11, createdAt: "12-02-2003" },
    { id: 12, createdAt: "12-02-2003", isActive: null },
  ]
)
// => [
//   { id: 2, createdAt: "12-02-2003", isActive: true },
//   { id: 4, createdAt: "12-02-2011", isActive: true },
//   { id: 6, createdAt: "12-02-2005", isActive: false },
//   { id: 5, createdAt: "12-02-2010", isActive: false },
//   { id: 12, createdAt: "12-02-2003", isActive: null },
//   { id: 11, createdAt: "12-02-2003" },
// ]
```

**v3:** custom transform/lens function - 1 param signature

- function receives value of assigned key and will apply default sorting on the result

```js
sortWith(
  {
    createdAt: source => new Date(source).getTime(),
  },
  [
    { id: 5, createdAt: "12-02-2010", isActive: false },
    { id: 4, createdAt: "12-02-2011", isActive: true },
    { id: 3, createdAt: "12-02-2001", isActive: false },
    { id: 6, createdAt: "12-02-2005", isActive: false },
    { id: 11, createdAt: "12-02-2003" },
  ]
)
// => [
//  { id: 3, createdAt: "12-02-2001", isActive: false },
//  { id: 11, createdAt: "12-02-2003" },
//  { id: 6, createdAt: "12-02-2005", isActive: false },
//  { id: 5, createdAt: "12-02-2010", isActive: false },
//  { id: 4, createdAt: "12-02-2011", isActive: true },
// ]
```

**v3.1:** With custom `direction`:

```js
sortWith({
  createdAt: [source => new Date(source).getTime(), "desc"],
})
```

I also added some input validation on `sortWith` (this is the first one I think):

- allows only "asc"/"desc" `direction`
- checks function signature, allows 1 and 2 params

## Checklist

- [x] Tests - use [Riteway](https://github.com/ericelliott/riteway), see [distinct.test.js](https://github.com/asd-xiv/m/blob/master/src/distinct/distinct.test.js)
- [x] JSDocs
- [x] Export in `src/index.js`

### CODE REVIEW

**Comment by andreidmt** [comment]
@dgilperez Added the rework I mentioned in #10. 

Thanks for opening the topic :+1:

**Comment by dgilperez** [comment]
Hey! Thanks for this :) 

I am having some trouble after the upgrade, probably my bad: 

```
console.log(
      [
        {
          position: 1,
          activityId: "a",
          id: "b",
        },
      ] |> sortWith({ position: "asc" })
    )
```

Fails with 

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
``` 

on `m/dist/sort/sort-with.js:101:42`

Any idea?

**Comment by dgilperez** [comment]
Ok, so this works

```
console.log(
      sortWith({ position: "asc" }, [
        {
          position: 1,
          activityId: "a",
          id: "b",
        },
      ])
    )
```

So it must be some issue with the type operator? 

I can of course open a new issue

**Comment by andreidmt** [comment]
It would appear I forgot to curry it :)

Fixed in [v6.3.1](https://github.com/asd-xiv/m/releases/tag/v6.3.1)

**Comment by dgilperez** [comment]
oh, of course! thanks for that, super quick.

**Pull request merged**
