### PR TITLE
feat!: support node v16 and v18, drop v14

### PR DESCRIPTION
**Pull request by andreidmt**
## Primary

1. https://github.com/asd-xiv/m/commit/73e65973e30a8b27e12eebcc2ee4ddc59cda4789 Update CircleCI executors and test jobs to use node v16 and v18
2. https://github.com/asd-xiv/m/commit/7a1d83132423537c204cec427fa400a95dde943f Upgrade all packages to latest release
3. https://github.com/asd-xiv/m/pull/23/commits/27c68ae0c34b187b95f1b830b6464874b9cd8b6b Switch commit message conventions to [convetional-commits](https://www.conventionalcommits.org) instead of [Angular](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit)

## Checklist

- [ ] ~Tests~ N/A
- [ ] ~JSDocs~ N/A
- [ ] ~Export in `src/index.js`~ N/A

### CODE REVIEW

**Comment by dgilperez** [comment]
Unfortunately, I am still on Node 14 ... any major reason not to support it? Is it blocking anything? 

As reference, Node 14 will EoL on mid 2023 https://nodejs.org/en/about/releases

**Comment by dgilperez** [comment]
I am looking into the upgrade to v16 (v18 is not available on Google Cloud, yikes). I am not sure how big of a hassle is that, but it looks harmless. 

#famouslastwords

**Comment by andreidmt** [comment]
> Unfortunately, I am still on Node 14 ... any major reason not to support it? Is it blocking anything?
> 
> As reference, Node 14 will EoL on mid 2023 https://nodejs.org/en/about/releases

My rules a bit simpler, current version that will be future LTS and current active LTS, also it's not healthy to wait and be forced to upgrade.

Right now 14 is 4 major version behind (a lot of performance gains, updated Node API) with `npm` also 2 major version (different package-lock format etc).

From what I remember, I believe this should be a seamless upgrade (true true, famous last words).

Would be nice if you can give this a try on a test env and rerun some tests. If it's not seamless, we can wait a bit and I'll only push the package bumps.

**Comment by dgilperez** [comment]
We're running v16 for a while on staging now, everything seems to work just fine ... I didn't upgrade any APIs or anything, but I guess we'll learn those as we go.

👍 good to go from our side

**Review by dgilperez — APPROVED** [review]
lgtm!

**Pull request merged**
